spring.application.name=spring-start-here-practice

server.port=9090

name.service.url=http://localhost:8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.initialization-mode=always